GET https://api.restful-api.dev/objects HTTP/1.1

###

GET http://localhost:8080/tasks HTTP/1.1

###

POST http://localhost:8080/tasks HTTP/1.1
content-type: application/json

{
    "title": "sample",
    "done": true
}

###

GET http://localhost:8080/tasks/2 HTTP/1.1

###