name: Build and test Go
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.24
        uses: actions/setup-go@v1
        with:
          go-version: 1.24

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Verify dependencies
        run: go mod verify

      - name: Run tests
        run: go test -v -json ./...

      - uses: mr-smithers-excellent/docker-build-push@v3
        name: Build & push Docker image
        with:
          image: kub5on/example
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}